<?php
/**
 * Created by IntelliJ IDEA.
 * User: yadallee
 * Date: 09/03/19
 * Time: 01:32
 */

namespace Personnes\Controller;

use Zend\Mvc\Controller\AbstractActionController;
use Zend\View\Model\ViewModel;


class MyController extends AbstractActionController
{
    public function indexAction()
    {
        return  $this->response->setContent("Hello world");// TODO: Change the autogenerated stub
    }

    public function templateAction()
    {
        $view = new ViewModel();
        return $view->setTemplate("MyTemplate");
    }
}